sudo: false
language: java
jdk:
- openjdk7
- oraclejdk8
- oraclejdk9

script:
- mvn clean install

after_success:
- mvn jacoco:prepare-agent test jacoco:report coveralls:report

cache:
  directories:
  - $HOME/.m2
